apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tpwernrf6-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tpwernrf6-nodejs 
  name: tpwernrf6-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tpwernrf6-nodejs 
